### ISSUE TITLE
Question : Does logspout resume where it left off ?

### ISSUE THREAD

**Issue by hibri** [gliderlabs/logspout#244]
If the logspout container is restarted does, logspout resume the log stream from where it left off ? 
Will I be able to catchup on logs that were missed ?
Running logspout under kubernetes with rancher.

**Comment by imriz** [comment]
I don't think so.
In https://github.com/gliderlabs/logspout/blob/master/router/pump.go#L171 the code chooses the Since value. It can be either now, or from the beginning (if backlog is enabled). So you can basically choose from duplicate logs, or lose some messages.
It worth mentioning that if InactivityTimeout kicks in (no logs seen from the docker logs stream for X duration), it will be smart enough to start more or less from where it stopped (*do note that there is still a very small window even here when logs could get lost, due to when and how the "since" parameter is calculated*).

**Comment by hibri** [comment]
@imriz Thanks. I figured as much while reading the code. Thanks for expanding on it.  I'm ok with taking a hit with duplicated logs, rather than loose them.
