### ISSUE TITLE
Papertrail stops gettings logs after an hour

### ISSUE THREAD

**Issue by tleyden** [gliderlabs/logspout#268]
I'm running logspout on docker cloud with a volume mount of `-v /var/run/docker.sock:/var/run/docker.sock` and a command line arg to point to `syslog://logs5.papertrailapp.com:3...`

It runs for about an hour and then logs mysteriously stop appearing in papertrail.  

Is there anything I can do to debug it?

**Comment by tleyden** [comment]
I should mention that I'm nowhere close to hitting the papertrail limit

**Comment by grydstedt** [comment]
Seeing this as well. Any resolution @tleyden?

**Comment by tleyden** [comment]
@grydstedt Unfortunately no.  Docker support told me to try a bigger instance, which I haven't done (partly because it just seems to sweep the issue under the carpet).

**Comment by timstallmann** [comment]
Think I may be seeing something similar here as well :/

**Comment by grydstedt** [comment]
Yeah, works for a couple of days of logging and then stops. I reached out to papertrail and they suggested these potential workarounds: 

- Make sure you're on the latest logspout. Currently, that's v3.1. If that doesn't fix it, it may be worth trying logspout:master, even though that's a prerelease.
- Point logspout at a local rsyslog server, which is configured to relay to Papertrail.
- Use Docker's built-in syslog driver instead of logspout. This requires access to the host, so that you can run dockerd with options like --log-driver=syslog and --log-opt syslog-address=tcp+tls://logsN.papertrailapp.com:99999. Also, it's got a downside that logs are no longer stored locally, even for the docker logs command – they're sent to syslog and that's all.

I'm already running logspout:master, so I might give setting up a rsyslog daemon a whirl

**Comment by michaelshobbs** [comment]
We have a couple PRs open on this. I am looking at testing them and hopefully releasing a new image soon

**Comment by michaelshobbs** [comment]
potentially related to #277

**Comment by luketurner** [comment]
I've also encountered this problem, and it was because Papertrail resets TCP connections after 15 minutes of inactivity. Go considers an ECONNRESET to be a "temporary" error, so the logspout does not try to recreate the connection, but instead keeps retrying sending data on the broken connection.

In terms of solutions, I'm using a logspout patch that makes ECONNRESET a permanent error (because it seems silly for it to be temporary). I also have it send the logs to a local rsyslog container, which is responsible for queueing logs and retrying if Papertrail goes down. Overall, this scheme's dramatically increased the stability of my logs.

**Comment by josegonzalez** [comment]
Seems like we would accept a patch for the `ECONNRESET` thing being permanent?

**Comment by luketurner** [comment]
Sure. I'm no Go expert, but I'll put a PR together.

**Comment by michaelshobbs** [comment]
I know we have at least one open PR on this subject. I am currently working on building out the test suite for this exact issue. Take a look at #253 and see if that might help in your case. (I **think** it's probably the same issue.)

**Comment by luketurner** [comment]
I think it would definitely help, but I think it's a slightly different issue. I made a PR for the specific issue with ECONNRESET: https://github.com/gliderlabs/logspout/pull/287. If you want, it might make sense to merge it into a larger PR affecting the whole retry/retryTemporary/resubmit section. Either way is fine with me.

**Comment by michaelshobbs** [comment]
Just saw it. Thanks! I'll write tests for both cases and get these merged ASAP.

**Comment by luketurner** [comment]
Awesome, thanks!

**Comment by michaelshobbs** [comment]
Potential fix + tests were merged in f18e503780b8f3abb3771ffaa97e5d2971199f9b
