### ISSUE TITLE
Client-side load-balancing

### ISSUE THREAD

**Issue by pradeepcloudstack** [gliderlabs/logspout#378]
We have a requirement for doing client-side load-balancing with logspout to avoid the load on the load-balancers. Currently, logspout is routing the logs to logstash servers which are front-ended by a load-balancer. The expectation is to be able to specify a list of server-ips (and port) in the ROUTE_URIS and logspout should randomly (or based on some algorithm) choose one of the server-ip

**Comment by gbolo** [comment]
hi @pradeepcloudstack 

This is not currently supported in `logspout`. I would suggest that you use DNS to accomplish something like this (round-robin DNS record) which perhaps can help spread the load better. I would suggest you also re-evaluate the use of a loadbalancer here, since that would be the best possible solution. Using a load balancer would also detect bad/down logstash servers and ensure that your logging infrastructure is more resilient to failures overall.

Closing this issue for now, as it appears that this enhancement request did not get any attention and is easily fixed with the suggestions above.
