### ISSUE TITLE
How logspout is diffrent from default docker drivers like GELF/syslog plugins 

### ISSUE THREAD

**Issue by dvyas** [gliderlabs/logspout#383]
Hi,

I am exploring logging tools to collect logs from docker containers. How logspout is different from docker logging drivers. For example: GELF plugin can also send logs to logstash.

**Comment by pablolibo** [comment]
look https://github.com/micahhausler/logspout-gelf

**Comment by gbolo** [comment]
@dvyas `logspout` is different from docker logging drivers because it allows you to keep the local logs (so the command `docker logs <container>` still works) while still shipping the container logs to a remote location. This is accomplished using the docker api (that's why `logspout` needs access to docker socket). I would say that this makes `logspout` more flexible in some situations. Try out both and you will spot the differences
