### ISSUE TITLE
logspout with TLS failure

### ISSUE THREAD

**Issue by harikum** [gliderlabs/logspout#387]
attempting to forward docker logs to central logstash server with TLS, without TLS the configuration works fine.

logstash enabled for ssl using self signed certificates

input {
  tcp {
    port => 5000
    type => syslog
    ssl_enable => "true"
    ssl_verify => false
    ssl_cert => "/etc/certs/logstash.crt"
    ssl_key => "/etc/certs/logstash.key"
  }

certificates staged locally on the client... and bind mounting them into the logspout container as per the documentation, but it fails to load, error indicate that its trying to use a local certificate instead of the custom certificate.

# ls -l /opt/logspout/certs/
total 8
-rw-r--r-- 1 root root 1704 Mar 23 16:32 ca.key
-rw-r--r-- 1 root root 1549 Mar 23 16:32 ca.pem

# docker run --name="logspout" -v /var/run/docker.sock:/var/run/docker.sock -v /opt/logspout/certs/:/mnt/ca/ gliderlabs/logspout:latest syslog+tls://host.domain.com:5000
# logspout v3.2.4 by gliderlabs
# adapters: udp tls raw syslog tcp
# options : persist:/mnt/routes
!! x509: certificate is valid for localhost.localdomain, not host.domain.com
#

**Comment by gbolo** [comment]
this issue is not related to logspout. This is a TLS misconfiguration on your end. This is due to your x509 server certificate being valid for valid for localhost.localdomain, not host.domain.com

create a new self-signed certficate which has a proper hostname (subject alternative name) instead of `localhost.localdomain` and make sure your client can reach the logging server via this new name.

Please close this issue

**Comment by gbolo** [comment]
fixed by #408
