### ISSUE TITLE
[kind question] how do we use /health (healthcheck)?

### ISSUE THREAD

**Issue by jmarcos-cano** [gliderlabs/logspout#430]
I see several places where it references "healthcheck", however I dont find anywhere that shows how to use it. 

im using a docker-compose file where I can definitely add a `healthcheck:` instruction

thanks in advance

**Comment by gbolo** [comment]
Hi @jmarcos-cano 

Seems like the healthcheck simply writes a static response:
```
// HealthCheck returns a http.Handler for the health check
func HealthCheck() http.Handler {
	r := mux.NewRouter()
	r.HandleFunc("/health", func(w http.ResponseWriter, req *http.Request) {
		w.Write([]byte("Healthy!\n"))
	})
	return r
}
```

Basically, it always returns a `200` status, with a body of `Healthy!\n`. Not sure how useful this is in a dockerfile if `logspout` is already PID1, since this response will ALWAYS be returned unless the process dies, in which case the whole container dies. But if you wish to use it in your dockerfile, you can periodically `curl` it with a `HEAD` method and confirm you get a `200` response status.

**Comment by jmarcos-cano** [comment]
@gbolo so to port 80? 

`curl -X HEAD http://localhost/health`

**Comment by gbolo** [comment]
@jmarcos-cano yes, also port can be controlled via env var:
```
PORT or HTTP_PORT - configure which port to listen on (default 80)
``
