### ISSUE TITLE
DNS resolution

### ISSUE THREAD

**Issue by sstarcher** [gliderlabs/logspout#47]
With the latest version of logspout I'm having DNS resolution issues.  I can resolve google.com over and over again and it resolves, but when I attempt to lookup a dns entry hosted by amazon it intermittently works.  We also have a local DNS server backed by consul and I also see intermittent issues.

I tried both using --net host and normal container networking
docker run -it --net host --entrypoint /bin/sh b4a89d11cec4

```
/ # nslookup logstash.service.consul
Server:    (null)
Address 1: ::1 ip6-localhost
Address 2: 127.0.0.1 localhost

Name:      logstash.service.consul
Address 1: 10.0.10.166 ip-10-0-10-166.ec2.internal
Address 2: 10.0.20.207 ip-10-0-20-207.ec2.internal
/ # nslookup logstash.service.consul
Server:    (null)
Address 1: ::1 ip6-localhost
Address 2: 127.0.0.1 localhost

nslookup: can't resolve 'logstash.service.consul': Name does not resolve
/ #
/ #
/ # nslookup logstash.service.consul
Server:    (null)
Address 1: ::1 ip6-localhost
Address 2: 127.0.0.1 localhost

nslookup: can't resolve 'logstash.service.consul': Name does not resolve
/ # nslookup logstash.service.consul
Server:    (null)
Address 1: ::1 ip6-localhost
Address 2: 127.0.0.1 localhost

nslookup: can't resolve 'logstash.service.consul': Name does not resolve
```

**Comment by progrium** [comment]
How are your DNS servers configured and what is the contents of your `resolv.conf` in the container and on the host? It turns out musl resolves DNS differently ... actually uses all configured DNS servers querying them in parallel using the first response it gets. Obviously this is problematic when one nameserver provides results the other doesn't. We've got some solutions to try but any more data you have would be helpful.

**Comment by sstarcher** [comment]
That would be my problem.  We have 2 consul dns servers that are the first 2 in our list that have the records for logstash.service.consul and we have a 3rd dns server that is last in the list that is an EC2 DNS server that would not have that entry.

**Comment by progrium** [comment]
Since you probably don't want to remove the EC2 DNS from the host just in
case, you can instead explicitly set the DNS servers for logspout to just
Consul as a temporary workaround.

On Thu, Feb 26, 2015 at 8:35 AM, Shane Starcher <notifications@github.com>
wrote:

> That would be my problem. We have 2 consul dns servers that are the first
> 2 in our list that have the records for logstash.service.consul and we have
> a 3rd dns server that is last in the list that is an EC2 DNS server that
> would not have that entry.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gliderlabs/logspout/issues/47#issuecomment-76187985>.
>



-- 
Jeff Lindsay
http://progrium.com

**Comment by sstarcher** [comment]
Yep that works.
