### ISSUE TITLE
Question - systemd journal?

### ISSUE THREAD

**Issue by bryantidd** [gliderlabs/logspout#51]
I'm trying to capture logs from CentOS 7 docker containers. They are sending data to systemd journal. What is the best way to proceed? Do I need to change the way all these containers do logging, or is there a way to support surfacing these logs via logspout?

I'm open to suggestions. Ultimately I want to ship these logs to Loggly, so I'd probably have to post process the logs somewhere like the docker daemon host to add in the customer token. I'm open to ideas on that too..like doing a little awk or something... Again appriciate any ideas on how to use logspout to accomplish all this.

**Comment by andyshinn** [comment]
The logs are captured from the container log stream. This should be independent of systemd. Is logspout not getting any of the log data?

**Comment by progrium** [comment]
Logspout will not collect logs from systemd. It will only collect from stdout and stderr of containers. Soon it will let you send logs to it via syslog as well. Otherwise, this is not supported.

**Comment by ebr** [comment]
@bryantidd, this actually does work for me on Ubuntu 16.04.1, with `gliderlabs/logspout:master` and `sendgridlabs/loggly-docker:latest`. 

In my setup: 
- loggly container listens on docker bridge's IP, port 514,
- logspout forwards to that IP and port,
- docker is configured with `--log-driver=journald`

since journald logs are available via `docker logs`, logspout accesses them just fine.

**Comment by bryantidd** [comment]
@ebr - yes, but that wasn't available at the time of asking the question...but thanks and yes, it is a working solution.
